version: '3.3'

services:
  aospace:
    privileged: true
    image: localhost/aospace-single:v1.0.0
    container_name: aospace-single
    restart: always
    ports:
      - "5678:5678"

    environment:
      AOSPACE_SINGLE_DOCKER_MODE: true
      AOSPACE_DATADIR: "/mnt/aospace"
